# 3. 优化器与参数更新
## forward & backward

- forward pass:compute loss
    loss = f(g(h(x))) #记录每一个节点的值
- compute local gradients
    - loss.backward():
        - compute all nodes(if the node satisfy requires_grad == True，非叶子叶节也满足)
        - backward pass , dLoss/dWeights
        - x.grad += dloss/dx: Chain Rule
- backward pass: compute dLoss/dWeights using the Chain Rule
    - optimizer.step()
        - x += -lr*x.grad() # a learning process
        - commonly, optim.zero_grad()——>loss.backward() # 在每个batch之前

In [1]:
import torch
import numpy
from torch. import nn

In [3]:
# criterion = nn.XXLoss()
# model = nn.XXNet()
# optimizer = torch.optim.Adam(model.parameters(),lr=0.001) # 只优化模型参数
# for _ in range(epochs):
#     for images, labels in data_loader:
#         output = model(images)
#         loss = criterion(output, label)
#         loss.zero_grad() # 对所有requires_grad==True 节点梯度清零
#         loss.backward() # 对所有requires_grad==True 节点反向传播
#         optimizer.step() # 对模型参数进行优化 model.parameters() -= lr*model.parameters()
        

### 举个例子

In [8]:
x = torch.tensor([1.,3],requires_grad=True)
w1 = torch.tensor([1.,1.],requires_grad=True)
y = w1*x
loss = y.sum()
optimizer = torch.optim.SGD([w1],lr=0.01)
optimizer.zero_grad() # 优化器优化方向每次都要清零
loss.backward()
optimizer.step()

In [10]:
x # 不是模型更新参数

tensor([1., 3.], requires_grad=True)

In [11]:
w1

tensor([0.9900, 0.9700], requires_grad=True)

In [12]:
w1.grad

tensor([1., 3.])

In [17]:
torch.tensor([1.,1.],requires_grad=True)-w1.grad*0.01 ==w1

tensor([True, True])