# BCELoss

In [41]:
import torch
import numpy as np
from torch import nn

### BCELoss Computation

- step1:接受的输入是经过sigmoid的网络输出。sigmoid
- step2:$$l_{i}=-(y_{i}log(\hat{y_{i}})+(1-y_{i})log(1-\hat{y_{i}}))
=-(y_{i}log(\sigma(z_{i}))+(1-y_{i})log(1-\sigma(z_{i})))$$
预测为1的概率和预测为0的概率最大
- step3:$$\frac{1}{n}{\sum}_{i}l_{i}$$


In [30]:
m = nn.Sigmoid()
loss = nn.BCELoss()
inputs = torch.randn(3, requires_grad=True)
targets = torch.empty(3).random_(2)
output = loss(m(inputs),targets)

In [31]:
inputs, targets, output

(tensor([-1.1387,  0.6041, -0.6029], requires_grad=True),
 tensor([0., 0., 0.]),
 tensor(0.5848, grad_fn=<BinaryCrossEntropyBackward0>))

In [32]:
m(inputs) # 输出是各自预测为1的概率

tensor([0.2426, 0.6466, 0.3537], grad_fn=<SigmoidBackward0>)

In [33]:
1/3*(-np.log(1-0.4626)-np.log(0.4595)-np.log(1-0.2108))

0.5451214749402727

backward

In [34]:
output.backward()
inputs.grad 

tensor([0.0809, 0.2155, 0.1179])

$$
\frac{\partial l_{i}}{\partial z{i}} = -(y_{i}(1-\sigma(z_{i}))-(1-y_{i})\sigma(z_{i})) = -(y_{i}-\sigma(z_{i}))
$$
化简结果表明是向实际标签更新

In [35]:
-(targets-m(inputs))/3

tensor([0.0809, 0.2155, 0.1179], grad_fn=<DivBackward0>)

# BECLoss vs. BCEWithLogitsLoss

- BCEWithLogitsLoss=sigmoid + BCELoss

In [37]:
loss2 = nn.BCEWithLogitsLoss()

In [39]:
loss2(inputs, targets) # 输入不经过Sigmoid = loss(m(inputs),targets)

tensor(0.5848, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

# CrossEntropyLoss

- 二分类与多分类
- 单输出和多输出
- sigmoid 和 softmax
- 都是通过cross entropy loss 计算

In [40]:
loss3 = nn.CrossEntropyLoss()