- Entropy: # 熵

$$ H(p)=-\sum_{i}p_{i}logp_{i} $$


- CrossEntropy

$$ H(p,q)=-\sum_{i}p_{i}logq_{i} $$

- KL Divergence # 相对熵
$$
\begin{align}
 D_{kl}(p||q)&=\sum_{i}p_{i}log\frac{p_{i}}{q_{i}} \\
               &=H(p,q)-H(p) 
\end{align}
$$

KL散度在机器学习中退化成log loss

- nn.KLDivLoss(reduction='batchmean')的api:
    - (input_log_softmax, target_shaped) # 首先标签和预测值都需要先取softmax变成概率分布，input预测值还默认需要log
- nn.CrossEntropyLoss()
    - ()

## e.g.1

In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
kl_loss = nn.KLDivLoss(reduction='batchmean')

In [7]:
inputs = torch.log(torch.FloatTensor([[1/3,1/3,1/3]])) #预测值q
target = torch.FloatTensor([[9/25,12/25,4/25]]) # 样本标签p

In [8]:
kl_loss(inputs, target) # Dkl(p||q)  两顺序排列是相反的

tensor(0.0853)

## e.g.2

In [39]:
kl_loss = nn.KLDivLoss(reduction='batchmean')
ce_loss = nn.CrossEntropyLoss()

In [40]:
inputs = torch.randn(3,5, requires_grad=True) # batch=3
target = torch.empty(3, dtype=torch.long).random_(5) # 样本标签
inputs, target

(tensor([[ 0.8955,  0.3146,  0.0945, -1.3011, -0.4158],
         [ 0.7525, -1.0168, -0.9943,  0.0556, -1.4012],
         [ 0.7580, -0.2224, -2.3352, -0.9218,  1.0977]], requires_grad=True),
 tensor([0, 4, 1]))

In [41]:
ce = ce_loss(inputs, target)
ce

tensor(1.9266, grad_fn=<NllLossBackward0>)

In [42]:
inputs_log_softmax = F.log_softmax(inputs, dim=1) #先对行作softmax再取log
inputs_log_softmax

tensor([[-0.8708, -1.4517, -1.6719, -3.0674, -2.1821],
        [-0.6724, -2.4417, -2.4192, -1.3693, -2.8261],
        [-1.1025, -2.0828, -4.1956, -2.7822, -0.7627]],
       grad_fn=<LogSoftmaxBackward0>)

In [47]:
target_shaped=torch.FloatTensor([[1,0,0,0,0],
                                 [0,0,0,0,1],
                                 [0,1,0,0,0]])

In [48]:
kl_loss(inputs_log_softmax,target_shaped)

tensor(1.9266, grad_fn=<DivBackward0>)

In [51]:
ce_loss(inputs,target_shaped)

tensor(1.9266, grad_fn=<DivBackward1>)

In [50]:
# ce_loss(inputs, target)-ce_loss(target_shaped, target)

tensor(1.0218, grad_fn=<SubBackward0>)